sudo: false

language:
    - php

php:
    - 5.3

env:
  - PHPCS_BRANCH=master
  - PHPCS_BRANCH=2.7.1
  - SHORT_OPEN_TAG=true

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: SHORT_OPEN_TAG=false

before_script:
    - export PHPCS_DIR=/tmp/phpcs
    - export PHPCS_BIN=$(if [[ $PHPCS_BRANCH == 3.0 ]]; then echo $PHPCS_DIR/bin/phpcs; else echo $PHPCS_DIR/scripts/phpcs; fi)
    - mkdir -p $PHPCS_DIR && git clone --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git -b $PHPCS_BRANCH $PHPCS_DIR
    - $PHPCS_BIN --config-set installed_paths $(pwd)
    - if [[ "$SHORT_OPEN_TAG" == "false" ]]; then echo "short_open_tag = Off" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
    - if [[ "$SHORT_OPEN_TAG" == "true" ]]; then echo "short_open_tag = On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

script:
    - if find . -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi;
    - phpunit --filter WordPress /tmp/phpcs/tests/AllTests.php
    # WordPress Coding Standards.
    # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
    # @link http://pear.php.net/package/PHP_CodeSniffer/
    # -p flag: Show progress of the run.
    # -s flag: Show sniff codes in all reports.
    # -v flag: Print verbose output.
    # -n flag: Do not print warnings. (shortcut for --warning-severity=0)
    # --standard: Use WordPress as the standard.
    # --extensions: Only sniff PHP files.
    - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -n . --standard=./bin/phpcs.xml --extensions=php; fi
